<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tavo Parra</title>

  <!-- Bootstrap -->
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/font-awesome.min.css">
  <link href="css/style.css" rel="stylesheet" />
</head>

<body>

  <div class="title">
    <div class="container">
      <div class="col-lg-12 welcome">
        <h1>Bienvenido</h1>
        <p><span>Este sitio está bajo construcción.</span><br>Vuelve pronto para acceder a un excelente contenido</p>
      </div>
    </div>
  </div>

  <div class="timer">
    <div class="container">
      <div class="col-md-6 col-md-offset-3">
        <div class="text-center">
          <!-- Countdown dashboard start -->
          <div id="countdown_dashboard">
            <div class="countDown">
              <div class="dash days_dash">
                <span class="dash_title">Días</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
              </div>

              <div class="dash hours_dash">
                <span class="dash_title">Horas</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
              </div>

              <div class="dash minutes_dash">
                <span class="dash_title">Minutos</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
              </div>

              <div class="dash seconds_dash">
                <span class="dash_title">Segundos</span>
                <div class="digit">0</div>
                <div class="digit">0</div>
              </div>
            </div>
          </div>
          <!-- Countdown dashboard end -->
        </div>
      </div>
    </div>
  </div>

  <!--<div class="container">
    <div class="col-lg-12">
      <form class="form-horizontal">
        <div class="text-center">
          <div class="subscribe">
            <form action="" method="POST" id="subscribe_form">
              <input type="text" name="email" id="email_field" class="faded" value="your@email.com" /> <input type="submit" id="subscribe_button" value="Send" />
            </form>
          </div>
        </div>
      </form>
    </div>
  </div>--!>

  <div class="social-icon">
    <div class="container">
      <div class="col-md-6 col-md-offset-3">
        <div class="text-center">
          <ul class="social-network">
            <li><a href="https://www.facebook.com/tavo.parra.7" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://www.twitter.com/tavo_pa" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://www.linkedin.com/in/octavio-parra-%C3%A1lvarez-2a3a5933/" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="https://www.youtube.com/channel/UC-fI4pLoGn31vofeR29S4SQ" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Footer start here -->
  <footer>
    <div class="col-md-6 col-md-offset-3">
      <div class="text-center">
        <div class="copyright">
          &copy; Tavo Parra.
          <div class="credits">
            Contacto: <a href="mailto:tavo.parra@hotmail.com">tavo.parra@hotmail.com</a>
          </div>
        </div>
      </div>
    </div>
  </footer>



  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="js/jquery-2.1.1.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="js/bootstrap.min.js"></script>
  <script language="Javascript" type="text/javascript" src="js/jquery.lwtCountdown-1.0.js"></script>
  <script language="Javascript" type="text/javascript" src="js/misc.js"></script>
  <script src="js/functions.js"></script>

</body>
</html>
